config/routes.rb
Rails.application.routes.draw do
  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
  devise_for :users
  resources :users, only: [:show, :edit, :update]
  resources :games, only: [:show, :new, :create] do
     resources :messages, only: [:create]
  end
  put 'games/place'
  root to: 'games#create'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ConnectFour</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= action_cable_meta_tag %>
  </head>

  <body>
    <div class="navbar">
    <% if user_signed_in? %>
      <%= image_tag current_user.avatar_url(24) %>
      <%= link_to current_user.email, user_path(current_user), :class => 'navbar-link' %>
      <%= link_to "Edit Account", edit_user_registration_path, :class => 'navbar-link' %> - 
      <%= link_to "Edit Profile", edit_user_path(current_user), :class => 'navbar-link' %> -
      <%= link_to 'New Game', new_game_path, { class: "navbar-link" } %> -
      <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
      <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
    </div>
    <%= yield %>
  </body>
</html>